version: 2
updates:
  - package-ecosystem: yarn
    directory: '/'
    schedule:
      day: monday
      interval: monthly
      time: '02:00'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 99
    target-branch: master
    commit-message:
      prefix: chore
      include: scope